
name: Ract CI

on: 
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: sudo apt install zip unzip
      - run: zip -r BuildArtifact.zip build

      - name: Upload artifact
        uses: zoispag/action-s3-upload-artifact@v1
        id: s3
        with:
              access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              bucket: ${{ secrets.AWS_BUCKET }}
              key: MyDockerBuild
              path: .\build\*

      - name: Output path
        run: echo ${{ steps.s3.outputs.object_path }}
