
name: Ract CI

on: 
  push:
    branches:
      - "master"
      - "Dev"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: sudo apt install zip unzip
      - run: zip -r BuildArtifact.zip build
     
      - name: action-upload-to-s3
        uses: wixplosives/action-upload-to-s3@v10
        env:
          Date: $(Get-Date -Format yyyyMMddhhmmss)
        with:
          accessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          awsBucket: ${{ secrets.AWS_BUCKET }}    
          s3Subfolder: MyBuild/${env.Date}
          sourceFolder: build
