
name: Ract CI

on: 
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: mkdir BuildArtifact
      - run: sudo apt install zip unzip
      - run: cp -R /build/* /BuildArtifact
      - run: zip -r BuildArtifact.zip BuildArtifact

      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: dsyadav50@gmail.com
          # from email name
          from: Neeraj Singh

      - name: Upload artifact
        uses: zoispag/action-s3-upload-artifact@v1
        id: s3
        with:
              access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              bucket: ${{ secrets.AWS_BUCKET }}
              bucket_root: Artifacts
              key: BuildArtifact.zip
              path: MyBuild/

      - name: Output path
        run: echo ${{ steps.s3.outputs.object_path }}
