
name: Ract CI

on: 
  push:
    branches:
      - "master"
      - "Dev"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: sudo apt install zip unzip
      - run: zip -r BuildArtifact.zip build
      
      - name: Upload S3
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          # aws key id
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws secret access key
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          # aws bucket name
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          # directory to upload
          source_dir: 'build'
          # destination directory for upload
          destination_dir: 'MyBuild'
           
